### PR TITLE
Micro optimization for SHA1

### PR DESCRIPTION
**Pull request by Shark64**
The original version of F0 from  the RFC uses andn insted of xor to compute the step and has a better instruction level parallelism (2 cycles vs 3) so use it for MAGIC_F0. Also use shorter opcodes where possibile and broadcast constants to reduce .data size

### CODE REVIEW

**Comment by gbtucker** [comment]
Thanks @Shark64. I'll take a look.

**Comment by dong-liuliu** [comment]
looks good, Shark.
Can you squash them together?

**Comment by gbtucker** [comment]
Also please add [signoff language](https://01.org/community/signed-process), name etc. in [contributing.](https://github.com/01org/isa-l_crypto/blob/master/CONTRIBUTING.md)

**Comment by Shark64** [comment]
The signoff etc must be in the pull request by pushing a new commit or i can put it here in the discussion? 
Also i'm not sure how to "squash" git commits together, sorry i'm a bit of a newbie with git.

**Comment by gbtucker** [comment]
No problem.  The following git commands should do it but make sure you read [signoff](https://01.org/community/signed-process).
`git config user.name "Your Real Name"`  ; Need your real name
`git rebase -i HEAD~3`
edit messge last two lines to start with 'f' instead of 'pick':
   pick 8176d49 use a more IPC friendly version of F1, broadcast constants to reduce size of data
   f 0c7fed0 fix operand order in PANDN
   f 7169771 formatting src code
`git commit -a --signoff --reset-author --amend` ; Can change the commit message here but please keep the first line brief, then blank line before details
`git push origin HEAD -f`

**Comment by Shark64** [comment]
Ok thanks, i've done it, let me know if everything is ok now :)

**Pull request merged**
